ALTER TABLE `User`
  MODIFY COLUMN `role` ENUM('USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN') NOT NULL DEFAULT 'USER';

ALTER TABLE `AdminAction`
  MODIFY COLUMN `action` ENUM(
    'REPORT_REVIEWING',
    'REPORT_DISMISSED',
    'REPORT_ACTIONED',
    'LISTING_HIDDEN',
    'LISTING_UNHIDDEN',
    'USER_SUSPENDED',
    'USER_UNSUSPENDED',
    'HUB_CREATED',
    'HUB_UPDATED',
    'HUB_DEACTIVATED',
    'HUB_REACTIVATED',
    'ID_VERIFICATION_APPROVED',
    'ID_VERIFICATION_REJECTED',
    'ROLE_CHANGED'
  ) NOT NULL;
